# Generated by Django 4.1.7 on 2023-03-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('usuario', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=300)),
            ],
        ),
    ]
